POST http://127.0.0.1:5000/recipe/recipes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNjg2Mzk4MywianRpIjoiZDQ3Yzc4MTgtMzgwZi00NGE4LTllMDYtOTcwNDBhYWYwNDEyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InNpbW8iLCJuYmYiOjE3MjY4NjM5ODMsImNzcmYiOiJlMDc4ZmE2Yy0yYjQwLTRlYmUtOTc3NS0yMjI3NjNiMjhiZjIiLCJleHAiOjE3MjY4NjQ4ODN9.8IjJVfsX-5RTAzaQ6qQQvx_-uCYo7MqCjBmB49sfjMc

{
  "title": "Recipe Title",
  "description": "This is a recipe description",
  "full_name": "John Doe",
  "cin": "CIN123456",
  "phone_number": "123456789",
  "email": "john@example.com",
  "age": 30,
  "gender": "Male",
  "state": "StateName",
  "city": "CityName",
  "address": "123 Main St",
  "marital_status": "Single",
  "nbr_of_children": 0,
  "occupation": "Chef",
  "salary": 4000.00
}
