"""Updated new Models

Revision ID: fe9bd38630de
Revises: 
Create Date: 2024-09-20 21:00:44.415826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9bd38630de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Bda bi ta3ti l'kolon 'full_name' b'nullable=True'
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cin', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('nbr_of_children', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('salary', sa.Float(), nullable=True))

    # N3mlu update 3la l'kolon jadid
    op.execute("UPDATE recipe SET full_name = 'Unknown' WHERE full_name IS NULL")

    # Daba nzido l'NOT NULL 3la l'kolon
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('full_name', nullable=False)
        batch_op.alter_column('cin', nullable=False)
        batch_op.alter_column('email', nullable=False)
        batch_op.alter_column('phone_number', nullable=False)
        batch_op.alter_column('age', nullable=False)
        batch_op.alter_column('gender', nullable=False)
        batch_op.alter_column('state', nullable=False)
        batch_op.alter_column('city', nullable=False)
        batch_op.alter_column('address', nullable=False)
        batch_op.alter_column('marital_status', nullable=False)
        batch_op.alter_column('occupation', nullable=False)
        batch_op.alter_column('salary', nullable=False)

        # Daba ndiru l'unique constraints
        batch_op.create_unique_constraint('uq_recipe_cin', ['cin'])
        batch_op.create_unique_constraint('uq_recipe_email', ['email'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('salary')
        batch_op.drop_column('occupation')
        batch_op.drop_column('nbr_of_children')
        batch_op.drop_column('marital_status')
        batch_op.drop_column('address')
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')
        batch_op.drop_column('email')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('cin')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
